# Generated by Django 5.2.14 on 2026-06-22 01:48

from datetime import datetime, timedelta, timezone

from django.db import migrations, models


def get_last_time_nagged_initial():
    return datetime.now(tz=timezone.utc) - timedelta(weeks=5)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_add_language_adjust_theme_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_time_nagged',
            field=models.DateTimeField(default=get_last_time_nagged_initial),
        ),
    ]
